security:
  oauth2:
    client:
      clientId: <ID do Aplicativo>      
      clientSecret: <Chave Secreta do Aplicativo>
      scope: email
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me?fields=email,id,name,picture


